### ISSUE TITLE
[Help wanted] How can I feed in precomputed gradients?

### ISSUE THREAD

**Issue by themightyoarfish** [noahgolmant/pytorch-hessian-eigenthings#13]
Since I'm iterating over the dataset and computing the first gradients anyway, it seems like a waste to do `torch.autograd.grad` again in `HVPOperator`, so I'm trying to figure out how to use gradients I already have.

So in my training procedure, I specify `loss.backward(create_graph=True, retain_graph=True)` and then capture gradients by `register_backward_hook()` on the model parameters. However, taking the second gradient in `HVPOperator.apply()` still fails with 
```
RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.
```
Would you have any idea how to accomplish this?

**Comment by noahgolmant** [comment]
I would have to see what the code looks like first. Off the top of my head: why do you use `register_backward_hook` to get the gradients? You could access them through `p.grad for p in model.parameters()`. This lets you aggregate / vectorize them the same way I'm doing it now with the `torch.autograd.grad` call.

If you are doing this during training, you would need to rewrite things so that it applies power iteration using only a single mini-batch. I am writing a utility to incrementally track the spectrum during training in #10, although it doesn't reuse gradients like that. You would have to test if a single batch still provides a reliable estimate.

**Comment by themightyoarfish** [comment]
Yeah my code is currently based off of that branch. I don't necessarily need an estimate only based on the current batch, but I want to avoid computing gradients twice.

I'm using hooks (actually `register_hook` on the weight and bias tensors currently) because I'm developing a tool which exports all kinds of things, not just gradients. But it shouldn't matter, should it? The tensors passed to the gradient hook should be the same as are assigned to the `.grad` attribute later, shouldn't they?

**Comment by themightyoarfish** [comment]
It turns out I simply misunderstood the error message. I thought that `Specify retain_graph=True when calling backward the first time.` referred to the initial call to `loss.backward()`, not the first of several calls to `torch.autograd.grad()` which are being done repeatedly in `HVPOperator.apply()`. Adding `retain_graph=True` there actually does what I need.
